#!/bin/bash
# session-state.sh - Session State 管理器 v2.1
# 基于 Claude Code sessionMemoryCompact.ts 改进
# 防止 compaction 丢失上下文，追踪摘要边界
# v2.1: 新增异步任务追踪，防止外部 API 调用丢失状态

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME/.openclaw/workspace}"
MEMORY_DIR="$WORKSPACE_DIR/memory"
STATE_FILE="$MEMORY_DIR/compact-state-$(date +%Y-%m-%d-%H%M).md"
LAST_SUMMARIZED_FILE="$MEMORY_DIR/.last_summarized_id"
PENDING_TASKS_FILE="$MEMORY_DIR/.pending_tasks"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_ok() { echo -e "${GREEN}[OK]${NC} $*"; }
log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }

#----------------------------------------------------------
# 写入 Session State
#----------------------------------------------------------
write_state() {
    local content="${1:-auto}"
    local custom_workstream="${2:-}"
    
    # 生成结构化的 Session Memory
    cat > "$STATE_FILE" << EOF
# Session State — $(date -u +%Y-%m-%dT%H:%M:%SZ)

_Generated by huo15-memory-evolution Session State Manager v2.1_

## Current Work
$(if [ -n "$custom_workstream" ]; then echo "$custom_workstream"; else echo "_正在进行的任务或工作流_"; fi)

## Pending Async Tasks
$(if [ -f "$PENDING_TASKS_FILE" ]; then
    grep -v "|complete$" "$PENDING_TASKS_FILE" 2>/dev/null | while IFS='|' read -r date id desc task_status; do
        echo "- [$task_status] $desc (ID: $id, 开始: $date)"
    done || echo "_无进行中的异步任务_"
else
    echo "_无进行中的异步任务_"
fi)

## Recent Decisions
$(if ls "$MEMORY_DIR/project/"*.md >/dev/null 2>&1; then
    find "$MEMORY_DIR/project" -name "*.md" -newer "$SKILL_DIR/SKILL.md" 2>/dev/null | head -3 | while read f; do
        head -5 "$f"
        echo "---"
    done
else
    echo "_暂无_"
fi)

## Open Tasks
$(if [ -f "$MEMORY_DIR/project/tasks-progress.md" ]; then
    grep -E "^\- \[ \]" "$MEMORY_DIR/project/tasks-progress.md" 2>/dev/null | head -5 || echo "- _暂无未完成任务_"
else
    echo "- _暂无任务追踪_"
fi)

## Key Context
$(if [ -f "$MEMORY_DIR/MEMORY.md" ]; then
    grep -A2 "^## " "$MEMORY_DIR/MEMORY.md" 2>/dev/null | head -20 || echo "_详见 MEMORY.md_"
else
    echo "_暂无_"
fi)

## Last Summarized
$(if [ -f "$LAST_SUMMARIZED_FILE" ]; then
    echo "Message ID: $(cat "$LAST_SUMMARIZED_FILE")"
    echo "File age: $(($(date +%s) - $(stat -f %m "$LAST_SUMMARIZED_FILE" 2>/dev/null || stat -c %Y "$LAST_SUMMARIZED_FILE" 2>/dev/null))) seconds"
else
    echo "_未设置_"
fi)

EOF
    log_ok "状态已写入: $(basename "$STATE_FILE")"
    echo "$STATE_FILE"
}

#----------------------------------------------------------
# 读取 Session State
#----------------------------------------------------------
read_state() {
    local state_file="${1:-}"
    
    if [ -z "$state_file" ]; then
        state_file=$(find "$MEMORY_DIR" -name "compact-state-*.md" -type f 2>/dev/null | head -1)
    fi
    
    if [ -n "$state_file" ] && [ -f "$state_file" ]; then
        cat "$state_file"
    else
        echo "No state file found."
    fi
}

#----------------------------------------------------------
# 注入 Session State（compaction 后恢复）
#----------------------------------------------------------
inject() {
    local state_file=$(find "$MEMORY_DIR" -name "compact-state-*.md" -type f 2>/dev/null | head -1)
    
    if [ -n "$state_file" ] && [ -f "$state_file" ]; then
        local file_age=$(($(date +%s) - $(stat -f %m "$state_file" 2>/dev/null || stat -c %Y "$state_file" 2>/dev/null)))
        
        # 超过 72 小时跳过
        if [ "$file_age" -gt 259200 ]; then
            log_warn "Session State 已过期（>72小时），跳过恢复"
            return 1
        fi
        
        echo ""
        echo "## === Session State ==="
        cat "$state_file"
        echo "## === End Session State ==="
        echo ""
        
        # 注入待追踪的异步任务状态
        if [ -f "$PENDING_TASKS_FILE" ]; then
            local pending_count
            pending_count=$(grep -cv "|complete$" "$PENDING_TASKS_FILE" 2>/dev/null | head -1 || echo "0")
            pending_count=${pending_count:-0}
            if [ "$pending_count" -gt 0 ] 2>/dev/null; then
                echo "## === Pending Async Tasks ==="
                get_pending_tasks
                echo "## === End Pending Tasks ==="
                echo ""
            fi
        fi
        
        log_info "已恢复 Session State（$((file_age / 3600)) 小时前）"
    fi
}

#----------------------------------------------------------
# 追踪最后摘要的消息 ID（防止重复摘要）
#----------------------------------------------------------
set_last_summarized() {
    local msg_id="${1:-}"
    if [ -z "$msg_id" ]; then
        log_warn "用法: session-state.sh set-last-summarized <message_id>"
        return 1
    fi
    echo "$msg_id" > "$LAST_SUMMARIZED_FILE"
    log_ok "已设置最后摘要 ID: $msg_id"
}

get_last_summarized() {
    if [ -f "$LAST_SUMMARIZED_FILE" ]; then
        cat "$LAST_SUMMARIZED_FILE"
    fi
}

#----------------------------------------------------------
# 检查是否需要新的摘要
#----------------------------------------------------------
check_threshold() {
    local state_file=$(find "$MEMORY_DIR" -name "compact-state-*.md" -type f 2>/dev/null | head -1)
    
    if [ -z "$state_file" ] || [ ! -f "$state_file" ]; then
        echo "NO_STATE"
        return
    fi
    
    local file_age=$(($(date +%s) - $(stat -f %m "$state_file" 2>/dev/null || stat -c %Y "$state_file" 2>/dev/null)))
    
    # 超过 30 分钟需要更新
    if [ "$file_age" -gt 1800 ]; then
        echo "NEEDS_UPDATE"
    else
        echo "CURRENT"
    fi
}

#----------------------------------------------------------
# 异步任务追踪
#----------------------------------------------------------

# 添加待追踪的异步任务
add_pending_task() {
    local task_id="$1"
    local task_desc="$2"
    local task_type="${3:-async}"
    
    if [ -z "$task_id" ] || [ -z "$task_desc" ]; then
        log_warn "用法: add_pending_task <task_id> <task_desc> [type]"
        return 1
    fi
    
    mkdir -p "$(dirname "$PENDING_TASKS_FILE")"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)|$task_id|$task_desc|$task_type" >> "$PENDING_TASKS_FILE"
    log_ok "添加待追踪任务: $task_desc (ID: $task_id)"
}

# 更新异步任务状态
update_pending_task() {
    local task_id="$1"
    local new_status="$2"
    
    if [ -z "$task_id" ] || [ -z "$new_status" ]; then
        log_warn "用法: update_pending_task <task_id> <new_status>"
        return 1
    fi
    
    if [ ! -f "$PENDING_TASKS_FILE" ]; then
        return
    fi
    
    local temp_file
    temp_file=$(mktemp)
    while IFS='|' read -r date id desc task_status; do
        if [ "$id" = "$task_id" ]; then
            echo "$date|$id|$desc|$new_status" >> "$temp_file"
        else
            echo "$date|$id|$desc|$task_status" >> "$temp_file"
        fi
    done < "$PENDING_TASKS_FILE"
    mv "$temp_file" "$PENDING_TASKS_FILE"
    log_ok "更新任务状态: $task_id -> $new_status"
}

# 列出所有待追踪任务
list_pending_tasks() {
    if [ ! -f "$PENDING_TASKS_FILE" ]; then
        echo "无待追踪任务"
        return
    fi
    
    echo "=== 待追踪的异步任务 ==="
    while IFS='|' read -r date id desc task_status; do
        echo "[$task_status] $date | $id | $desc"
    done < "$PENDING_TASKS_FILE"
}

# 获取待追踪任务详情
get_pending_tasks() {
    local filter_status="${1:-}"
    
    if [ ! -f "$PENDING_TASKS_FILE" ]; then
        return
    fi
    
    while IFS='|' read -r date id desc task_status; do
        if [ -z "$filter_status" ] || [ "$task_status" = "$filter_status" ]; then
            echo "[$task_status] $desc (ID: $id, 开始: $date)"
        fi
    done < "$PENDING_TASKS_FILE"
}

#----------------------------------------------------------
# 入口
#----------------------------------------------------------
case "${1:-}" in
    write)
        write_state "${2:-}" "${3:-}"
        ;;
    read)
        read_state "${2:-}"
        ;;
    inject)
        inject
        ;;
    set-last-summarized)
        set_last_summarized "${2:-}"
        ;;
    get-last-summarized)
        get_last_summarized
        ;;
    check)
        check_threshold
        ;;
    add-pending)
        add_pending_task "${2:-}" "${3:-}" "${4:-async}"
        ;;
    update-pending)
        update_pending_task "${2:-}" "${3:-}"
        ;;
    list-pending)
        list_pending_tasks
        ;;
    get-pending)
        get_pending_tasks "${2:-}"
        ;;
    help|--help|-h)
        echo "session-state.sh v2.1 - Session State 管理器"
        echo ""
        echo "用法:"
        echo "  session-state.sh write [内容] [工作流]      写入状态"
        echo "  session-state.sh read [文件]              读取状态"
        echo "  session-state.sh inject                   注入状态（compaction 后）"
        echo "  session-state.sh set-last-summarized <id> 设置最后摘要ID"
        echo "  session-state.sh get-last-summarized      获取最后摘要ID"
        echo "  session-state.sh check                    检查是否需要更新"
        echo "  session-state.sh add-pending <id> <描述>  添加待追踪异步任务"
        echo "  session-state.sh update-pending <id> <状态> 更新异步任务状态"
        echo "  session-state.sh list-pending             列出所有待追踪任务"
        echo "  session-state.sh get-pending [状态]       获取待追踪任务详情"
        ;;
    *) 
        echo "session-state.sh v2.1 - Session State 管理器"
        echo "用法: session-state.sh write|read|inject|set-last-summarized|get-last-summarized|check|add-pending|update-pending|list-pending|get-pending"
        ;;
esac
